config/routes.rb
Chimpslab::Application.routes.draw do
  resources :pages
  resources :venues
  resources :posts 
  resources :publications
  resources :people

  post "home/authenticate"
  get "home/index"
  get "home/logout"
  get "home/login"

  match "admin" => "home#admin"
  match "login" => "home#login"
  match "logout" => "home#logout"

  root :to => "home#index"

end

app/models/person.rb
# Copyright (c) 2011, Ian Li (http://ianli.com)
#
# The MIT License
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

class Person < ActiveRecord::Base
  POSITIONS = [
    "Faculty",
    "Program Assistant",
    "Postdoctoral Researcher",
    "Ph.D. Student",
    "Master's Student",
    "Undergraduate Student",
    "Visiting Researcher",
    "Research Staff",
    "Administrative Staff",
    "Staff",
    "Alumni"
  ]
  
  has_many :posts, :foreign_key => "author_id"
  has_and_belongs_to_many :publications, :order => "year DESC"
  
  # Paperclip attachment
  has_attached_file :avatar,
    :styles => {
      :thumb  => "100x100#",
      :small  => "200x200#",
      :medium => "400x400#"
    },
    :default_url => "/images/v1/no_avatar_92x92.png"
  
  # Pretty URLs
  def to_param
    self.alias
  end
  
  # Validations
  validates_presence_of :name
  validates_uniqueness_of :name, :case_sensitive => false
  validates_length_of :name, :maximum => 100
  
  validates_presence_of :alias
  validates_length_of :alias, :within => 3..15
  validates_uniqueness_of :alias, :case_sensitive => false
  validates_format_of :alias, :with => /\A[\w_]+\z/, :message => "must only have letters, numbers, and underscores."
  
  validates_presence_of :position
  
  # After Save
  after_save :assign_publications
  
  private
    
    def assign_publications
      publications = Publication.find :all
      
      person_name = self.name.strip
      
      publications.each do |publication|
        publication.authors_list.each do |author_name|
          if author_name.strip == person_name and not publication.people.find_by_name(person_name)
            publication.people << self
          end
        end
      end
    end
end

# == Schema Information
#
# Table name: people
#
#  id                  :integer         not null, primary key
#  alias               :string(255)
#  name                :string(255)
#  email               :string(255)
#  emaildisplay        :string(255)
#  url                 :string(255)
#  position            :string(255)
#  description         :text
#  created_at          :datetime
#  updated_at          :datetime
#  avatar_file_name    :string(255)
#  avatar_content_type :string(255)
#  avatar_file_size    :integer
#  avatar_updated_at   :datetime
#

app/controllers/people_controller.rb
# Copyright (c) 2011, Ian Li (http://ianli.com)
#
# The MIT License
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

class PeopleController < ApplicationController
  
  before_filter :auth_required, :except => [:index, :show]
  
  # CRUD
  # ------
  
  # GET /people
  # GET /people.xml
  def index
    @people = Person.all
    @people_by_position = @people.group_by(&:position)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @people }
    end
  end

  # GET /people/1
  # GET /people/1.xml
  def show
    @person = Person.find_by_alias(params[:id])
    @publications = @person.publications
    @posts = @person.posts

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @person }
    end
  end

  # GET /people/new
  # GET /people/new.xml
  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find_by_alias(params[:id])
  end

  # POST /people
  # POST /people.xml
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        flash[:notice] = 'Person was successfully created.'
        format.html { redirect_to(@person) }
        format.xml  { render :xml => @person, :status => :created, :location => @person }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @person.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.xml
  def update
    @person = Person.find_by_alias(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        flash[:notice] = 'Person was successfully updated.'
        format.html { redirect_to(@person) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @person.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.xml
  def destroy
    @person = Person.find_by_alias(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to(people_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form-back.html.erb
<%= form_for(@person, :html => { :multipart => true }) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="span-4">
    	<%= f.label :name %>
	</div>
	<div class="span-14 last">
	    <%= f.text_field :name, :class => "text" %>
	</div>
	<hr class="space" />
	
	<div class="span-4">
    	<%= f.label :alias %>
	</div>
	<div class="span-14 last">
	    <%= f.text_field :alias, :class => "text" %><br/>
		This person's profile page: http://cmuchimps.org/<b id="alias">ALIAS</b>
	</div>
	<hr class="space" />
  
  <div class="span-4">
    <label for="emaildisplay">Email Display</label>
	</div>
	<div class="span-14 last">
    <%= f.text_field :emaildisplay, :class => "text" %><br/>
    This is how your e-mail will render in your profile: <b id="emailal">email alias</b>
  </div>
	<hr class="space" />

	<div class="span-4">
    	<%= f.label :email %>
	</div>
	<div class="span-14 last">
	    <%= f.text_field :email, :class => "text" %>
	</div>
	<hr class="space" />

	<div class="span-4">
    	<%= f.label :url %>
	</div>
	<div class="span-14 last">
	    <%= f.text_field :url, :class => "text" %>
	</div>
	<hr class="space" />
	
	<div class="span-4">
    	<%= f.label :position %>
	</div>
	<div class="span-4 append-10 last">
		<%= f.select :position, Person::POSITIONS %>
	</div>
	<hr class="space" />

	<div class="span-4">
    	<%= f.label :description %>
	</div>
	<div class="span-14 last">
	    <%= f.text_area :description %>
	</div>
	<hr class="space" />
	
	<div class="span-4">
    	<%= f.label :avatar %>
	</div>
	<div class="span-14 last">
	    <%= f.file_field :avatar %>
	</div>
	<hr class="space" />
	
	<div class="prepend-4 span-14 last">
	    <%= f.submit(@person.new_record? ? 'Create' : 'Update', :class => "submit") %>
	</div>
<% end %>

<% content_for :sb do %>
	<h2>Formatting your description</h2>
	
	<%= render :partial => "layouts/textile_examples" %>
<% end %>

<% content_for :js do %>
<script type="text/javascript">
	$(document).ready(function() {
		var value = $("#person_alias").val();
    var emval = $("#person_emaildisplay").val();

    if (value.length > 0) {
			$("#alias").html(value);
    }
    if (emval.length > 0) {
      $("#emailal").html(emval);
    }
	});
	
	$("#person_alias").keyup(function() {
		var value = $(this).val();
		$("#alias").html(value);
  });

  $("#person_emaildisplay").keyup(function() {
    var value = $(this).val();
    $("#emailal").text(""+value);
  });
</script>
<% end %>

app/views/people/_form.html.erb
<%= form_for @person, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend>Create New Person</legend>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field span5' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :alias, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :alias, :class => 'text_field span5' %><br/>
      This person's profile page: http://cmuchimps.org/<b id="alias">ALIAS</b>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :email, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :email, :class => 'text_field span5' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :emaildisplay, 'Email Display', :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :emaildisplay, :class => 'text_field span5' %><br/>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :url, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :url, :class => 'text_field span5' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :position, :class => 'control-label' %>
      <div class="controls">
        <%= f.select :position, Person::POSITIONS, :class => 'text_field span5' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :description, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :description, :class => 'text_area span5' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :avatar, :class => 'control-label' %>
      <div class="controls">
        <%= f.file_field :avatar, :class => 'text_field span5' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', people_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>



<% content_for :sb do %>
	<h2>Formatting your description</h2>
	
	<%= render :partial => "layouts/textile_examples" %>
<% end %>

<% content_for :js do %>
<script type="text/javascript">
	$(document).ready(function() {
		var value = $("#person_alias").val();

    if (value.length > 0) {
			$("#alias").html(value);
    }
	});
	
	$("#person_alias").keyup(function() {
		var value = $(this).val();
		$("#alias").html(value);
  });
</script>
<% end %>

app/views/people/edit.html.erb
<%= render :partial => 'form' %>

app/views/people/index.html.erb
<% content_for :title do %>People<% end %>

<% Person::POSITIONS.each do |position| %>
	<% next unless @people_by_position.has_key?(position) %>
	
  <div class="row">
    <h2 id="<%= position.parameterize %>"><%= position %></h2>
  </div>
    
    <% @people_by_position[position].each_slice(4) do |three| %>
      <div class="row">
        <% three.each do |person| %>
          <div class="span2">
            <div class="person_image">
              <%= link_to (image_tag person.avatar.url(:thumb)), person %>
            </div>
            <div class="person_link">
              <%= link_to person.name, person %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>

	<% reset_cycle("columns") %>
<% end %>

<% content_for :sb do %>
	<% if authorized? %>
		<h2>Actions</h2>
		<p>
			<%= link_to 'New person', new_person_path %>
		</p>
	<% end %>

	<h2>Positions</h2>
	<ul class="bulletless">
		<% Person::POSITIONS.each do |position| %>
			<li><%= link_to position, :anchor => position.parameterize %></li>
		<% end %>
	</ul>
<% end %>

app/views/people/new.html.erb
<%= render :partial => 'form' %>

app/views/people/show.html.erb
<% content_for :title do %><%= @person.name %><% end %>
<div class="row">
  <div class="span2">
    <%= image_tag @person.avatar.url(:small), :width => "140px" %>
  </div>
  <div class="span5">
    <h1><%= @person.name %></h1>

    <p>
      <%= @person.position %><br/>
      <%= mail_to @person.email, @person.emaildisplay, :encode => "javascript" %><br/>
      <%= link_to @person.url, @person.url %>
    </p>
  </div>
</div>

<p><em><%= textilize(@person.description).html_safe %></em></p>

<% unless @publications.empty? %>
	<h2>Publications</h2>
  <table class="table table-striped">
    <% @publications.each do |publication| %>
      <%= render :partial => "publications/listing", 
          :locals => {
            :publication => publication,
            :people => Person.all
          } %>
    <% end %>
  </table>
<% end %>

<% unless @posts.empty? %>
	<h2>Posts</h2>
  <% @posts.each do |post| %>
    <%= render :partial => "posts/listing", :locals => { :post => post } %>
  <% end %>
<% end %>

<% content_for :sb do %>
	<% if authorized? %>
		<h2>Actions</h2>
		<p>
			<%= link_to 'Edit', edit_person_path(@person) %> <span class="pipe">|</span>
			<%= link_to 'Destroy', @person, :confirm => 'Are you sure?', :method => :delete %>
		</p>
	<% end %>
<% end %>