config/routes.rb
Chimpslab::Application.routes.draw do
  resources :pages
  resources :venues
  resources :posts 
  resources :publications
  resources :people

  post "home/authenticate"
  get "home/index"
  get "home/logout"
  get "home/login"

  match "admin" => "home#admin"
  match "login" => "home#login"
  match "logout" => "home#logout"

  root :to => "home#index"

end

app/models/publication.rb
# Copyright (c) 2011, Ian Li (http://ianli.com)
#
# The MIT License
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

class Publication < ActiveRecord::Base
  KINDS = [
    "Book", "Book Chapter", "Full Paper", "Workshop Paper", 
    "Journal Article", "Work in Progress", "Ph.D. Thesis", 
    "Master's Thesis"
  ].sort
  
  validates_presence_of :kind
  validates_presence_of :authors
  validates_presence_of :title
  validates_presence_of :venue_name
  validates_presence_of :year
  validates_numericality_of :year
  
  has_and_belongs_to_many :people
  
  belongs_to :venue, :counter_cache => true
  
  # Paperclip
  has_attached_file :pdf
  
  def to_param
    "#{id}-#{title.parameterize}"
  end
  
  # Returns an array of the list of author names.
  def authors_list
    self.authors.split("\n").delete_if { |a| a.blank? }.map { |a| a.strip }
  end
  
  # Humanized Attributes
  # http://henrik.nyh.se/2007/12/change-displayed-column-name-in-rails-validation-messages
  HUMANIZED_ATTRIBUTES = {
    :venue_name => "Venue"
  }

  def self.human_attribute_name(attr)
    HUMANIZED_ATTRIBUTES[attr.to_sym] || super
  end
end




# == Schema Information
#
# Table name: publications
#
#  id               :integer         not null, primary key
#  kind             :string(255)
#  authors          :text
#  title            :string(255)
#  venue_id         :integer
#  venue_name       :string(255)
#  year             :integer
#  abstract         :text
#  created_at       :datetime
#  updated_at       :datetime
#  pdf_file_name    :string(255)
#  pdf_content_type :string(255)
#  pdf_file_size    :integer
#  pdf_updated_at   :datetime
#

app/controllers/publications_controller.rb
# Copyright (c) 2011, Ian Li (http://ianli.com)
#
# The MIT License
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

class PublicationsController < ApplicationController
  
  before_filter :auth_required, :except => [:index, :show]
  
  # CRUD
  # ------
  
  # GET /publications
  # GET /publications.xml
  def index
    @publications = Publication.all
    @publications_by_year = @publications.group_by(&:year).sort.reverse
    @people = Person.find(:all)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @publications }
    end
  end

  # GET /publications/1
  # GET /publications/1.xml
  def show
    @publication = Publication.find(params[:id])
    @people = Person.find(:all)

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @publication }
    end
  end

  # GET /publications/new
  # GET /publications/new.xml
  def new
    @publication = Publication.new(:kind => "Full Paper")

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @publication }
    end
  end

  # GET /publications/1/edit
  def edit
    @publication = Publication.find(params[:id])
  end

  # POST /publications
  # POST /publications.xml
  def create
    @publication = Publication.new(params[:publication])

    respond_to do |format|
      if @publication.save
        flash[:notice] = 'Publication was successfully created.'
        format.html { redirect_to(@publication) }
        format.xml  { render :xml => @publication, :status => :created, :location => @publication }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @publication.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /publications/1
  # PUT /publications/1.xml
  def update
    @publication = Publication.find(params[:id])

    respond_to do |format|
      if @publication.update_attributes(params[:publication])
        flash[:notice] = 'Publication was successfully updated.'
        format.html { redirect_to(@publication) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @publication.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1
  # DELETE /publications/1.xml
  def destroy
    @publication = Publication.find(params[:id])
    @publication.destroy

    respond_to do |format|
      format.html { redirect_to(publications_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/publications_helper.rb
module PublicationsHelper
  def link_to_authors(authors_list, people)
    authors_list.map { |author|
      person = nil
      people.each do |p|
        if author == p.name.strip
          person = p
          break
        end
      end
      person ? link_to(author, person) : author
    }.to_sentence
  end
end

app/views/publications/_form-back.html.erb
<% form_for(@publication, :html => { :multipart => true }) do |f| %>
	<%= f.error_messages %>

	<div class="span-4">
		<%= f.label :kind %>
	</div>
	<div class="span-4">
		<%= select_tag :kind, options_for_select(Publication::KINDS << "Other:", @publication.kind) %>
	</div>
	<div class="span-10 last">
		<%= f.text_field :kind, :class => "text", :style => "display:none;"  %>
	</div>
	<hr class="space" />
	
	<div class="span-4">
		<%= f.label :authors %>
		<p class="small">
			Each author on a separate line.
			For consistency, format should be
			<code>first last</code>, <i>e.g.</i>:
			<i>Anind K. Dey</i>
		</p>
	</div>
	<div class="span-6">
		<%= f.text_area :authors, :style => "height:100px;" %>
	</div>
	<div class="span-4">
		<p class="small">
			Use the canonical names of members so that their names are automatically linked to their profiles.
		</p>
	</div>
	<div class="span-4 last">
		<ul class="bulletless small" style="padding:5px;height:100px;overflow-y:auto;color:#666;background-color:#eee;">
			<% Person.find(:all).each do |p| %>
				<li><%= p.name %></li>
			<% end %>
		</ul>
	</div>
	<hr class="space" />
	
	<div class="span-4">
		<%= f.label :title %>
	</div>
	<div class="span-14 last">
		<%= f.text_field :title, :class => "text" %>
	</div>
	<hr class="space" />
	
	<div class="span-4">
		<%= f.label :venue_name %>
	</div>
	<div class="span-14 last">
		<% venue_names = Venue.find(:all, :conditions => "publications_count > 0").map { |v| v.name } %>
		<%= select_tag :venue_name, options_for_select(venue_names << "Other:", @publication.venue_name) %><br/>
		<%= f.text_field :venue_name, :class => "text", :style => "display:none;" %>
		<p class="small" style="margin-bottom:0">
			Use the name of the conference instead of the name of the proceedings,
			<i>e.g., CHI vs. Proceedings of The ACM Conference on Human Factors in Computing Systems.</i>
		</p>
	</div>
	<hr class="space" />
	
	<div class="span-4">
		<%= f.label :year %>
	</div>
	<div class="span-4 append-10 last">
		<%= f.text_field :year, :class => "text" %>
	</div>
	<hr class="space" />
	
	<div class="span-4">
		<%= f.label :abstract %>
		<p class="small">
			You can format the abstract using
			<%= link_to "Textile", "http://blog.thought-mesh.net/static/docs/mtmanual_textile2.html", :target => "_new" %>.	
		</p>
	</div>
	<div class="span-14 last">
		<%= f.text_area :abstract, :style => "height:200px;" %>
	</div>
	<hr class="space" />
	
	<div class="span-4">
		<%= f.label :pdf %>
	</div>
	<div class="span-14 last">
		<%= f.file_field :pdf %>
	</div>
	<hr class="space" />
	
	<div class="prepend-4 span-14 last">
		<%= f.submit(@publication.new_record? ? 'Create' : 'Update', :class => "submit") %>
	</div>
<% end %>

<% content_for :js do %>
	<script type="text/javascript">
		function select_other(select_id, text_field_id) {
			// Prepare the event handler to the select.
			$(select_id).change(function() {
				var value = $(this).val();
				if (value == "Other:") {
					$(text_field_id)
						.show()
						.focus();
				} else {
					$(text_field_id)
						.val(value)
						.hide();
				}
			});
			
			// Check if the option exists.
			var option = $(text_field_id).val();
			var option_exists = false;
			$(select_id + " option").each(function() {
				if ($(this).html() == option) {
					option_exists = true;
					return false;
				}
			});
			
			// If not show, the text field.
			if (!option_exists) {
				$(select_id).val("Other:").change();
			}
		}
		
		$(document).ready(function() {
			select_other("#kind", "#publication_kind");
      select_other("#venue_name", "#publication_venue_name");
      $("#content_background").height($("#content").height());
      $("#content").offset({top: $("#content_background").offset().top});
      $("#ft").offset({top: $("#content_background").offset().top+$("#content_background").height()+35});
		});
	</script>
<% end %>

<% content_for :sb do %>
	<h2>Formatting your abstract</h2>
	
	<%= render :partial => "layouts/textile_examples" %>
<% end %>

app/views/publications/_form.html.erb
<%= form_for @publication, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend>Create New Publication</legend>

    <div class="control-group">
      <%= f.label :title, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :title, :class => 'text_field span5' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :kind, "Type:", :class => 'control-label' %>
      <div class="controls">
        <%= f.select :kind, options_for_select(Publication::KINDS << "Other:", @publication.kind), :class => 'text_field span5' %>
        <%= f.text_field :kind, :class => "text_field span5", :style => "display:none;", :id => 'kind'  %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :authors, :class => 'control-label' %>
      <div class="controls">
        <p class="small">
          Each author on a separate line.
          For consistency, format should be
          firstname middle-initial. lastname, <i>e.g.</i>:
          <i>Jason I. Hong</i>
        </p>
        <%= f.text_area :authors, :class => 'text_area span5', :style => "height:100px;" %>
        <p class="small">
          Use the canonical names of members so that their names are automatically linked to their profiles.
        </p>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :venue_name, :class => 'control-label' %>
      <div class="controls">
        <% venue_names = Venue.where("publications_count > 0").map { |v| v.name } %>
        <%= f.select :venue_name, options_for_select(venue_names << "Other:", @publication.venue_name), :class => 'text_field span5' %>
        <%= f.text_field :venue_name, :class => "text_field span5", :style => "display:none;", :id => 'venue_name' %>
        <p class="small" style="margin-bottom:0">
          Use the name of the conference instead of the name of the proceedings,
          <i>e.g., CHI vs. Proceedings of The ACM Conference on Human Factors in Computing Systems.</i>
        </p>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :year, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :year, :class => 'number_field span5' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :abstract, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :abstract, :class => 'text_area span5' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :pdf, :class => 'control-label' %>
      <div class="controls">
        <%= f.file_field :pdf, :class => 'file_field span5' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', publications_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>



<% content_for :js do %>
	<script type="text/javascript">
		function select_other(select_id, text_field_id) {
			// Prepare the event handler to the select.
			$(select_id).change(function() {
				var value = $(this).val();
				if (value == "Other:") {
					$(text_field_id)
						.show()
						.focus();
				} else {
					$(text_field_id)
						.val(value)
						.hide();
				}
			});
			
			// Check if the option exists.
			var option = $(text_field_id).val();
			var option_exists = false;
			$(select_id + " option").each(function() {
				if ($(this).html() == option) {
					option_exists = true;
					return false;
				}
			});
			
			// If not show, the text field.
			if (!option_exists) {
				$(select_id).val("Other:").change();
			}
		}
		
		$(document).ready(function() {
			select_other("#publication_kind", "#kind");
      select_other("#publication_venue_name", "#venue_name");
		});
	</script>
<% end %>

<% content_for :sb do %>
	<h2>Formatting your abstract</h2>
	
	<%= render :partial => "layouts/textile_examples" %>
<% end %>

app/views/publications/_listing.html.erb
<tr>
  <td><%= link_to publication.title, publication, :class => "_title" %></td>
  <td><%= link_to_authors(publication.authors_list, people).html_safe %></td>
  <td><%=h publication.venue_name %>, <%=h publication.year %> </td>
  <td><%= publication.kind %></td>
  <td>
    <% if publication.pdf.exists? %>
      <%= link_to "<i class=\"icon-file\"></i>".html_safe, publication.pdf.url %>
    <% end %>
  </td>
</tr>

app/views/publications/edit.html.erb
<%= render :partial => 'form' %>

app/views/publications/index.html.erb
<% content_for :title do %>Publications<% end %>
<% content_for :head do %>
<style type="text/css">
.pub>._title {
	font-weight:bold;
}
</style>
<% end %>

<h1>Publications</h1>

<% @publications_by_year.each do |year, publications| %>
	<h2 id="<%= year %>"><%= year %></h2>
  <table class="table table-striped">
    <% publications.each do |publication| %>
      <%= render :partial => "publications/listing", 
          :locals => {
            :publication => publication,
            :people => @people
          } %>
    <% end %>
  </table>
<% end %>


<% content_for :sb do %>
	<% if authorized? %>
		<h2>Actions</h2>
		<p>
			<%= link_to 'New publication', new_publication_path %>
		</p>
	<% end %>

	<h2>Year</h2>
	<ul class="bulletless">
		<% @publications_by_year.each do |year, publications| %>
			<li><%= link_to year, :anchor => year %></li>
		<% end %>
	</ul>
<% end %>

app/views/publications/new.html.erb
<%= render :partial => 'form' %>

app/views/publications/show.html.erb
<% content_for :title do %><%= @publication.title %><% end %>

<h1><%= @publication.title %></h1>

<div class="row">
  <div class="span1">
    <b>Authors</b>
  </div>
  <div class="span5">
    <%= link_to_authors @publication.authors_list, @people %>
  </div>
</div>

<div class="row">
  <div class="span1">
    <b>Venue</b>
  </div>
  <div class="span5">
    <%= @publication.venue_name %>
  </div>
</div>

<div class="row">
  <div class="span1">
    <b>Year</b>
  </div>
  <div class="span5">
    <%= @publication.year %>
  </div>
</div>


<% unless @publication.abstract.blank? %>
  <div class="row">
    <div class="span1">
      <b>Abstract</b>
    </div>
    <div class="span5">
      <%= @publication.abstract %>
    </div>
  </div>
<% end %>


<h2>Comments</h2>
<!-- Facebook Comments -->
<div id="fb-root"></div>
<script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script>
<fb:comments href="<%= request.url %>" numposts="10" width="620"></fb:comments>

<% content_for :sb do %>
	<% if authorized? %>
		<h2>Actions</h2>
		<p>
			<%= link_to 'Edit', edit_publication_path(@publication) %> <span class="pipe">|</span>
			<%= link_to 'Destroy', @publication, :confirm => 'Are you sure?', :method => :delete %>
		</p>
	<% end %>
	
	<h2>Share</h2>
	
	<!-- Twitter Button -->
	<a href="http://twitter.com/share" class="twitter-share-button" data-count="horizontal">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
	
	<!-- Facebook Like Button -->
	<iframe src="http://www.facebook.com/plugins/like.php?href=<%= CGI.escape(request.url) %>&amp;layout=standard&amp;show_faces=true&amp;width=200&amp;action=like&amp;colorscheme=light&amp;height=80" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:200px; height:80px;" allowTransparency="true"></iframe>
<% end %>