config/routes.rb
Chimpslab::Application.routes.draw do
  resources :pages
  resources :venues
  resources :posts 
  resources :publications
  resources :people

  post "home/authenticate"
  get "home/index"
  get "home/logout"
  get "home/login"

  match "admin" => "home#admin"
  match "login" => "home#login"
  match "logout" => "home#logout"

  root :to => "home#index"

end

app/models/venue.rb
# Copyright (c) 2011, Ian Li (http://ianli.com)
#
# The MIT License
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

class Venue < ActiveRecord::Base
  validates_presence_of :name
  validates_uniqueness_of :name
  
  has_many :publications, :order => "year DESC"
  
  def to_param
    "#{id}-#{name.parameterize}"
  end
end


# == Schema Information
#
# Table name: venues
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  publications_count :integer         default(0)
#  created_at         :datetime
#  updated_at         :datetime
#

app/controllers/venues_controller.rb
# Copyright (c) 2011, Ian Li (http://ianli.com)
#
# The MIT License
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

class VenuesController < ApplicationController
  before_filter :auth_required
  
  # GET /venues
  # GET /venues.xml
  def index
    @venues = Venue.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @venues }
    end
  end

  # GET /venues/1
  # GET /venues/1.xml
  def show
    @venue = Venue.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @venue }
    end
  end

  # GET /venues/new
  # GET /venues/new.xml
  def new
    @venue = Venue.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @venue }
    end
  end

  # GET /venues/1/edit
  def edit
    @venue = Venue.find(params[:id])
  end

  # POST /venues
  # POST /venues.xml
  def create
    @venue = Venue.new(params[:venue])

    respond_to do |format|
      if @venue.save
        flash[:notice] = 'Venue was successfully created.'
        format.html { redirect_to(@venue) }
        format.xml  { render :xml => @venue, :status => :created, :location => @venue }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @venue.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /venues/1
  # PUT /venues/1.xml
  def update
    @venue = Venue.find(params[:id])

    respond_to do |format|
      if @venue.update_attributes(params[:venue])
        flash[:notice] = 'Venue was successfully updated.'
        format.html { redirect_to(@venue) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @venue.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /venues/1
  # DELETE /venues/1.xml
  def destroy
    @venue = Venue.find(params[:id])
    
    if @venue.publications_count > 0
      flash[:notice] = 'Venue cannot be deleted because it has publications.'
      respond_to do |format|
        format.html { redirect_to(@venue) }
        format.xml  { head :forbidden }
      end
    else
      @venue.destroy

      respond_to do |format|
        format.html { redirect_to(venues_url) }
        format.xml  { head :ok }
      end
    end
  end
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/venues/_form.html.erb
<%= form_for @venue, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> /Venue</legend>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :publications_count, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :publications_count, :class => 'number_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', venues_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/venues/edit.html.erb
<%= render :partial => 'form' %>

app/views/venues/index.html.erb
<h1>Venues</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Publication Count</th>
    </tr>
  </thead>
  <tbody>
    <% @venues.each do |venue| %>
      <tr>
        <td><%= link_to venue.name, venue_path(venue) %></td>
        <td><%= venue.publications.length %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<% content_for :sb do %>
	<% if authorized? %>
		<h2>Actions</h2>
		<p>
			<%= link_to 'New Venue', new_venue_path %>
		</p>
	<% end %>
<% end %>

app/views/venues/new.html.erb
<%= render :partial => 'form' %>

app/views/venues/show.html.erb
<h1>/Venue</h1>

<p>
  <b>Name</b><br>
  <%= @venue.name %>
</p>

<p>
  <b>Publications count</b><br>
  <%= @venue.publications_count %>
</p>

<div class="form-actions">
  <%= link_to 'Back', venues_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_venue_path(@venue), :class => 'btn' %>
  <%= link_to 'Delete', venue_path(@venue), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>