config/routes.rb
Chimpslab::Application.routes.draw do
  resources :pages
  resources :venues
  resources :posts 
  resources :publications
  resources :people

  post "home/authenticate"
  get "home/index"
  get "home/logout"
  get "home/login"

  match "admin" => "home#admin"
  match "login" => "home#login"
  match "logout" => "home#logout"

  root :to => "home#index"

end

app/views/layouts/_textile_examples.html.erb
<p>
	You can use
	<%= link_to "Textile", "http://blog.thought-mesh.net/static/docs/mtmanual_textile2.html", :target => "_new" %>
	for formatting.
</p>

<ul class="bulletless">
	<li><code>__italics__</code> &nbsp; <i>italics</i></li>
	<li><code>*bold*</code> &nbsp; <b>bold</b></li>
	<li>
		<code>"link":http://google.com</code> &nbsp; <a href="http://google.com">link</a>
		<hr class="space" />
	</li>
	<li>
		Headings (leave a blank line after)<br/>
		<code>
		<ul class="bulletless" style="margin-bottom:5px;line-height:1.1em;">
			<li>h1. 1st-level heading</li>
			<li>h2. 2nd-level heading</li>
			<li>h3. 3rd-level heading</li>
		</ul>
		</code>
		<hr class="space" />
	</li>
	<li>
		Unordered list<br/>
		<code>
		<ul class="bulletless" style="margin-bottom:5px;line-height:1.1em;">
			<li>* an item</li>
			<li>* another item</li>
			<li>** second level</li>
		</ul>
		</code>
		<hr class="space" />
	</li>
	<li>
		Ordered list<br/>
		<code>
		<ul class="bulletless" style="margin-bottom:5px;line-height:1.1em;">
			<li># an item</li>
			<li># another item</li>
			<li>## second level</li>
		</ul>
		</code>
	</li>
</ul>

app/views/layouts/application-backup.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta property="fb:app_id" content="224017034329277" />
  <title>Chimpslab</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
	<%= stylesheet_link_tag 'chimpslab/test' %>

<%= yield :head %>

</head>
<body>

  <div id="all" class="all">
    <div id="leftNav" class="leftNav">
      <div class="chimptopleft" id="chimplogo">
        <a id="chimpslogo" class="logo" href="/" title="CHIMPS Lab">
            <h1>CHIMPS Lab</h1>
            <img src="/assets/vchimps/chimps-logo.png"/>
            <img src="/assets/vchimps/chimps-logo_on.png" class="_on"/>
          </a>
        </div>

        <div class="divider" id="leftNavDivider">
          <center><img border="0" src="/assets/vchimps/divider.gif" width="220"/></center>
        </div>

        
        <div id="mainnav">
          <ul>
            <li><%= link_to 'Home', root_path, :class => ((controller_name == "home" or controller_name == "pages") ? "selected" : nil) %></li>
            <li><%= link_to "Blog", posts_path, :class => (controller_name == "posts" ? "selected" : nil)  %></li>
            <li><%= link_to "People", people_path, :class => (controller_name == "people" ? "selected" : nil)  %></li>
            <li><%= link_to "Publications", publications_path, :class => (controller_name == "publications" ? "selected" : nil)  %></li>
            <% if authorized? %>
              <li class="admin">
                <%= link_to "Admin", admin_path, :class => "selected" %>
                <ul>
                  <li><%= link_to "Pages", pages_path %></li>
                  <li><%= link_to "Venues", venues_path %></li>
                  <li><%= link_to "Logout", logout_path %></li>
                </ul>
              </li>
            <% end %>
          </ul>
        </div>
      </td>
    </div>
   
    <!-- Content -->
    <div id="maincont" class="maincont">
      <div id="content_background" class="container container_wrap container_with_sb_bg"></div>
      <div id="content" class="container container_wrap container_with_sb">
        <div id="bd" class="span-18">
          <%= yield %>
        </div>
        <div class="sb span-6 last">
          <div style="padding-left:20px;">
            <%= yield :sb %>
          </div>
        </div>
      </div>


      <!-- Flash Notice -->
      <% if flash[:notice] %>
        <div id="flash" class="container container_wrap">
          <div class="span-18">
            <%= flash[:notice] %>
          </div>
          <div class="span-6 last">
            <a href="#" id="close_flash">&times;</a>
          </div>
        </div>
        <script type="text/javascript">
          $("#close_flash").click(function(e) {
            e.preventDefault();
            $('#flash').slideUp("normal");
          });
          
          $(document).ready(function() {
            setTimeout(function() {
              $('#flash').slideUp("normal");
            }, 5000);
          });
        </script>
      <% end %>
    </div>
    <!-- Footer -->
    <div id="ftcontainer" class="ftcontainer">
      <div id="ft" class="container container_wrap">
        <div class="span-12">
          <%= link_to "Home", root_url %> <span class="pipe">|</span>
          <%= link_to "Blog", posts_url %> <span class="pipe">|</span>
          <%= link_to "People", people_url %> <span class="pipe">|</span>
          <%= link_to "Publications", publications_url %>
        </div>
        <div class="span-12 last" style="text-align:right">
          &copy; <%= Date.today.strftime("%Y") %> 
          <%= link_to "CHIMPS Lab @ HCII, CMU", root_url %>.
          All rights reserved.
          <span class="pipe">|</span>
          
          <% if authorized? %>
            <%= link_to 'Logout', logout_path %>
          <% else %>
            <%= link_to 'Login', login_path %>
          <% end %>
        </div>
      </div>
  </div>

      <script type="text/javascript">
        $(document).ready(function() {
          var cont = $("#content");
          var cont_bg = $("#content_background");
          $(cont_bg).height(cont.height());
          $(cont_bg).width(cont.width());
          $(cont).offset($(cont_bg).offset());
          $(cont_bg).css("z-index",0);
          //fix maincont
          //var maincnt = $("#maincont");
          //maincnt.height(cont.height());
          //fix footer
          var ft = $("#ft");
          ft.offset({ top: (cont.offset().top+cont.height()), left: cont.offset().left});
          //ft.offset({ top: (ft.offset().top+40) });
        });

        $(window).resize(function() {
          $("#ft").offset({ left: $("#content").offset().left });
        });
        

        $(window).load(function() {
          $("#ft").offset({top: $("#ft").offset().top + 40});
        });
        
        var set = false;
        $(window).mousemove(function(event) {
          $("#content").resize();
          
          if (!set && $("#fb_widget").children().children().size() > 0) {
            $("#fb_widget").children().children().click(function() {
              $("#content").resize();
            });


            $("#fb_widget").children().children().mouseenter(function() {
              $("#content").resize();
            });

            $("#fb_widget").children().children().mouseleave(function() {
              $("#content").resize();
            });

            $("#fb_widget").children().children().mousehover(function() {
              $("#content").resize();
            });
            set=true;
          }
        });
        

        $("#content").resize(function() {
            $("#content_background").height($("#content").height());
            $("#content").offset({top: $("#content_background").offset().top});
            $("#ft").offset({top: $("#content_background").offset().top + $("#content_background").height()+40});
        });


      </script>
  </div> <!-- End Container -->

<!-- Javascripts -->
<%= yield :js %>

<!-- Analytics -->
<%= render :partial => "layouts/analytics" %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CHIMPS Lab</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- Le fav and touch icons -->
    <link href="images/favicon.ico" rel="shortcut icon">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
          <div class="container">
          <a class="brand" href="/">CHIMPS Lab</a>
            <ul class="nav pull-right">
              <li><%= link_to("<i class=\"icon-home\"></i>Home".html_safe, root_path) %></li>
              <li><%= link_to "<i class=\"icon-book\"></i>Blog".html_safe, posts_path  %></li>
                <li><%= link_to "<i class=\"icon-user\"></i>People".html_safe, people_path  %></li>
                <li><%= link_to "<i class=\"icon-list-alt\"></i>Publications".html_safe, publications_path  %></li>
            </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span8">
              <%= yield %>
            </div>
            <div class="span4">
              <div class="well sidebar-nav">
                <%= yield :sb %>
              </div><!--/.well -->
            </div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->

      <div class="row">
        <div class="span12 bordered">
          <% if authorized? %>
            <div class="btn-group">
              <%= link_to 'Logout', logout_path, :class => 'btn btn-warning pull-left' %>
              <%= link_to 'Pages', pages_path, :class => 'btn btn-warning pull-left' %>
              <%= link_to 'Venues', venues_path, :class => 'btn btn-warning pull-left' %>
            </div>
          <% else %>
            <%= link_to 'Login', login_path, :class => 'btn btn-warning pull-left' %>
          <% end %>
          <p class="pull-right">&copy; CHIMPS Lab 2012</p>
        </div>
      </div>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <%= yield :js %>

  </body>
</html>

app/views/layouts/application_backup.html.erb
<!DOCTYPE html>
<!--
 * CHIMPS Lab @ HCII, CMU
 * Design by Sauvik Das, 2011
-->
<html>
<head>
	<!-- Facebook Comments Application ID -->
	<meta property="fb:app_id" content="148223135240277" />
	
	<title><%= (str = yield :title) ? "#{str} - " : "" %>CHIMPS Lab @ HCII, CMU</title>
	<!-- Blueprint -->
	<link rel="stylesheet" href="/stylesheets/cw20gw20cc24/screen.css" type="text/css" media="screen, projection"  />
	<link rel="stylesheet" href="/stylesheets/cw20gw20cc24/print.css" type="text/css" media="print" />    
	<!--[if IE]><link rel="stylesheet" href="/stylesheets/cw20gw20cc24/ie.css" type="text/css" media="screen, projection" /><![endif]-->
	
	<%= stylesheet_link_tag 'chimpslab/main' %>
	
	<% if request.env["RAILS_ENV"] == "production" %>
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.0/jquery.min.js" type="text/javascript"></script>
	<% else %>
		<script src="/javascripts/jquery-1.5.js" type="text/javascript"></script>
	<% end %>
	
	<%= yield :head %>
</head>
<body>
	
<!-- Header -->
<div id="hd" class="container container_wrap">
	<!-- User Nav -->
	<div class="nav span-6 last">
	</div>
	
	<a id="chimpslab_logo" class="logo" href="/" title="CHIMPS Lab">
		<h1>CHIMPSLab</h1>
		<img src="/images/v1/hd_logo_chimps.png" />
		<img src="/images/v1/hd_logo_chimps_on.png" class="_on" />
	</a>
	
	<a id="hcii_logo" class="logo" href="http://www.hcii.cmu.edu/" title="Human-Computer Interaction Institute" target="_blank">
		<h1>Human-Computer Interaction Institute</h1>
		<img src="/images/v1/hd_logo_chimps.png" />
		<img src="/images/v1/hd_logo_chimps_on.png" class="_on" />
	</a>
	
	<a id="cmu_logo" class="logo" href="http://www.cmu.edu/" title="Carnegie Mellon University" target="_blank">
		<h1>Carnegie Mellon University</h1>
		<img src="/images/v1/hd_logo_chimps.png" />
		<img src="/images/v1/hd_logo_chimps_on.png" class="_on" />
	</a>
</div>

<div id="mainnav" class="container container_wrap">
	<ul>
		<li><%= link_to "Home", root_path, :class => ((controller_name == "home" or controller_name == "pages") ? "selected" : nil) %></li>
		<li><%= link_to "Blog", posts_path, :class => (controller_name == "posts" ? "selected" : nil)  %></li>
		<li><%= link_to "People", people_path, :class => (controller_name == "people" ? "selected" : nil)  %></li>
		<li><%= link_to "Publications", publications_path, :class => (controller_name == "publications" ? "selected" : nil)  %></li>
		<% if authorized? %>
			<li class="admin">
				<%= link_to "Admin", admin_path, :class => "selected" %>
				<ul>
					<li><%= link_to "Pages", pages_path %></li>
					<li><%= link_to "Venues", venues_path %></li>
					<li><%= link_to "Logout", logout_path %></li>
				</ul>
			</li>
		<% end %>
	</ul>
</div>

<!-- Flash Notice -->
<% if flash[:notice] %>
	<div id="flash" class="container container_wrap">
		<div class="span-18">
			<%= flash[:notice] %>
		</div>
		<div class="span-6 last">
			<a href="#" id="close_flash">&times;</a>
		</div>
	</div>
	<script type="text/javascript">
		$("#close_flash").click(function(e) {
			e.preventDefault();
			$('#flash').slideUp("normal");
		});
		
		$(document).ready(function() {
			setTimeout(function() {
				$('#flash').slideUp("normal");
			}, 5000);
		});
	</script>
<% end %>

<!-- Body and Sidebar -->

<div id="content_background" class="container container_wrap container_with_sb_bg"></div>
<div id="content" class="container container_wrap container_with_sb">
	<div id="bd" class="span-18">
		<%= yield %>
	</div>
	<div class="sb span-6 last">
		<div style="padding-left:20px;">
			<%= yield :sb %>
		</div>
	</div>
</div>
<script type="text/javascript">
  $(document).ready(function() {
    var cont = $("#content");
    var cont_bg = $("#content_background");
    $(cont_bg).height(cont.height());
    $(cont_bg).width(cont.width());
    $(cont).offset($(cont_bg).offset());
    $(cont_bg).css("z-index",0);
    var ftoff = $("#ft").offset();
    $("#ft").offset({ top: (ftoff.top-$(cont).height()-40), left: ftoff.left}); //margin is 40 px for some reason. Not really sure where this is specified in the CSS, so it shall be a magic number for now
});
</script>

<!-- Footer -->
<div id="ft" class="container container_wrap">
	<div class="span-12">
		<%= link_to "Home", root_url %> <span class="pipe">|</span>
		<%= link_to "Blog", posts_url %> <span class="pipe">|</span>
		<%= link_to "People", people_url %> <span class="pipe">|</span>
		<%= link_to "Publications", publications_url %>
	</div>
	<div class="span-12 last" style="text-align:right">
		&copy; <%= Date.today.strftime("%Y") %> 
		<%= link_to "CHIMPS Lab @ HCII, CMU", root_url %>.
		All rights reserved.
		<span class="pipe">|</span>
		
		<% if authorized? %>
			<%= link_to 'Logout', logout_path %>
		<% else %>
			<%= link_to 'Login', login_path %>
		<% end %>
	</div>
</div>

<hr class="doublespace" />

<!-- Javascripts -->
<%= yield :js %>

<!-- Analytics -->
<%= render :partial => "layouts/analytics" %>

</body>
</html>

app/views/layouts/application_test.html.erb
<!DOCTYPE html>
<!--
 * CHIMPS Lab @ HCII, CMU
 * Design by Sauvik Das, 2011
-->
<html>
<head>
	<!-- Facebook Comments Application ID -->
	<meta property="fb:app_id" content="148223135240277" />
	
	<title><%= (str = yield :title) ? "#{str} - " : "" %>CHIMPS Lab @ HCII, CMU</title>
	<!-- Blueprint -->
	<link rel="stylesheet" href="/stylesheets/cw20gw20cc24/screen.css" type="text/css" media="screen, projection"  />
	<link rel="stylesheet" href="/stylesheets/cw20gw20cc24/print.css" type="text/css" media="print" />    
	<!--[if IE]><link rel="stylesheet" href="/stylesheets/cw20gw20cc24/ie.css" type="text/css" media="screen, projection" /><![endif]-->
	
	<%= stylesheet_link_tag 'chimpslab/test' %>
	
	<% if request.env["RAILS_ENV"] == "production" %>
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.0/jquery.min.js" type="text/javascript"></script>
	<% else %>
		<script src="/javascripts/jquery-1.5.js" type="text/javascript"></script>
	<% end %>
	
	<%= yield :head %>
</head>
<body>

<table border="0" cellpadding="0" cellspacing="0" width="100%">
  <tr> <!-- Header cells -->
    <td align="left" valign="top" width="244">
      <div class="chimptopleft" id="chimplogo">
        <a id="chimpslogo" class="logo" href="/" title="CHIMPS Lab">
          <h1>CHIMPS Lab</h1>
          <img src="/images/vchimps/chimps-logo.png"/>
          <img src="/images/vchimps/chimps-logo_on.png" class="_on"/>
        </a>
      </div>

      <div class="divider" id="leftNavDivider">
        <img border="0" src="/images/vchimps/divider.gif" width="244"/>
      </div>

      
      <div id="mainnav">
        <ul>
          <li><%= link_to "Home", root_path, :class => ((controller_name == "home" or controller_name == "pages") ? "selected" : nil) %></li>
          <li><%= link_to "Blog", posts_path, :class => (controller_name == "posts" ? "selected" : nil)  %></li>
          <li><%= link_to "People", people_path, :class => (controller_name == "people" ? "selected" : nil)  %></li>
          <li><%= link_to "Publications", publications_path, :class => (controller_name == "publications" ? "selected" : nil)  %></li>
          <% if authorized? %>
            <li class="admin">
              <%= link_to "Admin", admin_path, :class => "selected" %>
              <ul>
                <li><%= link_to "Pages", pages_path %></li>
                <li><%= link_to "Venues", venues_path %></li>
                <li><%= link_to "Logout", logout_path %></li>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
      <div id="lftNavLogos">
        <a id="hcii_logo" class="logo" href="http://www.hcii.cmu.edu/" title="Human-Computer Interaction Institute" target="_blank">
          <h1>Human-Computer Interaction Institute</h1>
          <img src="/images/vchimps/hd_logo_chimps.png" />
          <img src="/images/vchimps/hd_logo_chimps_on.png" class="_on" />
        </a>
        <a id="cmu_logo" class="logo" href="http://www.cmu.edu/" title="Carnegie Mellon University" target="_blank">
          <h1>Carnegie Mellon University</h1>
          <img src="/images/vchimps/hd_logo_chimps.png" />
          <img src="/images/vchimps/hd_logo_chimps_on.png" class="_on" />
        </a>
      </div>
    </td>

    <!-- Content -->
    <td>
      <div id="content_background" class="container container_wrap container_with_sb_bg"></div>
      <div id="content" class="container container_wrap container_with_sb">
        <div id="bd" class="span-18">
          <%= yield %>
        </div>
        <div class="sb span-6 last">
          <div style="padding-left:20px;">
            <%= yield :sb %>
          </div>
        </div>
      </div>
      <script type="text/javascript">
        $(document).ready(function() {
          var cont = $("#content");
          var cont_bg = $("#content_background");
          $(cont_bg).height(cont.height());
          $(cont_bg).width(cont.width());
          $(cont).offset($(cont_bg).offset());
          $(cont_bg).css("z-index",0);
          var ftoff = $("#ft").offset();
          $("#ft").offset({ top: (ftoff.top-$(cont).height()-40), left: ftoff.left}); //margin is 40 px for some reason. Not really sure where this is specified in the CSS, so it shall be a magic number for now
      });
      </script>


      <!-- Flash Notice -->
      <% if flash[:notice] %>
        <div id="flash" class="container container_wrap">
          <div class="span-18">
            <%= flash[:notice] %>
          </div>
          <div class="span-6 last">
            <a href="#" id="close_flash">&times;</a>
          </div>
        </div>
        <script type="text/javascript">
          $("#close_flash").click(function(e) {
            e.preventDefault();
            $('#flash').slideUp("normal");
          });
          
          $(document).ready(function() {
            setTimeout(function() {
              $('#flash').slideUp("normal");
            }, 5000);
          });
        </script>
      <% end %>
    </td>
  </tr>
  <!-- Footer -->
  <tr>
    <td></td>
    <td>
      <div id="ft" class="container container_wrap">
        <div class="span-12">
          <%= link_to "Home", root_url %> <span class="pipe">|</span>
          <%= link_to "Blog", posts_url %> <span class="pipe">|</span>
          <%= link_to "People", people_url %> <span class="pipe">|</span>
          <%= link_to "Publications", publications_url %>
        </div>
        <div class="span-12 last" style="text-align:right">
          &copy; <%= Date.today.strftime("%Y") %> 
          <%= link_to "CHIMPS Lab @ HCII, CMU", root_url %>.
          All rights reserved.
          <span class="pipe">|</span>
          
          <% if authorized? %>
            <%= link_to 'Logout', logout_path %>
          <% else %>
            <%= link_to 'Login', login_path %>
          <% end %>
        </div>
      </div>
    </td>
  </tr>
</table>

<!-- Javascripts -->
<%= yield :js %>

<!-- Analytics -->
<%= render :partial => "layouts/analytics" %>

</body>
</html>

app/views/layouts/application_test_2.html.erb
<!DOCTYPE html>
<!--
 * CHIMPS Lab @ HCII, CMU
 * Design by Sauvik Das, 2011
-->
<html>
<head>
	<!-- Facebook Comments Application ID -->
	<meta property="fb:app_id" content="148223135240277" />
	
	<title><%= (str = yield :title) ? "#{str} - " : "" %>CHIMPS Lab @ HCII, CMU</title>
	<!-- Blueprint -->
	<link rel="stylesheet" href="/stylesheets/cw20gw20cc24/screen.css" type="text/css" media="screen, projection"  />
	<link rel="stylesheet" href="/stylesheets/cw20gw20cc24/print.css" type="text/css" media="print" />    
	<!--[if IE]><link rel="stylesheet" href="/stylesheets/cw20gw20cc24/ie.css" type="text/css" media="screen, projection" /><![endif]-->
	
	<%= stylesheet_link_tag 'chimpslab/test' %>
	
	<% if request.env["RAILS_ENV"] == "production" %>
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.0/jquery.min.js" type="text/javascript"></script>
	<% else %>
		<script src="/javascripts/jquery-1.5.js" type="text/javascript"></script>
	<% end %>
	
	<%= yield :head %>
</head>
<body>

  <div id="all" class="all">
    <div id="leftNav" class="leftNav">
      <div class="chimptopleft" id="chimplogo">
          <a id="chimpslogo" class="logo" href="/" title="CHIMPS Lab">
            <h1>CHIMPS Lab</h1>
            <img src="/images/vchimps/chimps-logo.png"/>
            <img src="/images/vchimps/chimps-logo_on.png" class="_on"/>
          </a>
        </div>

        <div class="divider" id="leftNavDivider">
          <img border="0" src="/images/vchimps/divider.gif" width="244"/>
        </div>

        
        <div id="mainnav">
          <ul>
            <li><%= link_to "Home", root_path, :class => ((controller_name == "home" or controller_name == "pages") ? "selected" : nil) %></li>
            <li><%= link_to "Blog", posts_path, :class => (controller_name == "posts" ? "selected" : nil)  %></li>
            <li><%= link_to "People", people_path, :class => (controller_name == "people" ? "selected" : nil)  %></li>
            <li><%= link_to "Publications", publications_path, :class => (controller_name == "publications" ? "selected" : nil)  %></li>
            <% if authorized? %>
              <li class="admin">
                <%= link_to "Admin", admin_path, :class => "selected" %>
                <ul>
                  <li><%= link_to "Pages", pages_path %></li>
                  <li><%= link_to "Venues", venues_path %></li>
                  <li><%= link_to "Logout", logout_path %></li>
                </ul>
              </li>
            <% end %>
          </ul>
        </div>
        <div id="lftNavLogos">
          <a id="hcii_logo" class="logo" href="http://www.hcii.cmu.edu/" title="Human-Computer Interaction Institute" target="_blank">
            <h1>Human-Computer Interaction Institute</h1>
            <img src="/images/vchimps/hd_logo_chimps.png" />
            <img src="/images/vchimps/hd_logo_chimps_on.png" class="_on" />
          </a>
          <a id="cmu_logo" class="logo" href="http://www.cmu.edu/" title="Carnegie Mellon University" target="_blank">
            <h1>Carnegie Mellon University</h1>
            <img src="/images/vchimps/hd_logo_chimps.png" />
            <img src="/images/vchimps/hd_logo_chimps_on.png" class="_on" />
          </a>
        </div>
      </td>
    </div>
   
    <!-- Content -->
    <div id="content" class="content">
      <div id="content_background" class="container container_wrap container_with_sb_bg"></div>
      <div id="content" class="container container_wrap container_with_sb">
        <div id="bd" class="span-18">
          <%= yield %>
        </div>
        <div class="sb span-6 last">
          <div style="padding-left:20px;">
            <%= yield :sb %>
          </div>
        </div>
      </div>
      <script type="text/javascript">
        $(document).ready(function() {
          var cont = $("#content");
          var cont_bg = $("#content_background");
          $(cont_bg).height(cont.height());
          $(cont_bg).width(cont.width());
          $(cont).offset($(cont_bg).offset());
          $(cont_bg).css("z-index",0);
          var ftoff = $("#ft").offset();
          $("#ft").offset({ top: (ftoff.top-$(cont).height()-40), left: ftoff.left}); //margin is 40 px for some reason. Not really sure where this is specified in the CSS, so it shall be a magic number for now
      });
      </script>


      <!-- Flash Notice -->
      <% if flash[:notice] %>
        <div id="flash" class="container container_wrap">
          <div class="span-18">
            <%= flash[:notice] %>
          </div>
          <div class="span-6 last">
            <a href="#" id="close_flash">&times;</a>
          </div>
        </div>
        <script type="text/javascript">
          $("#close_flash").click(function(e) {
            e.preventDefault();
            $('#flash').slideUp("normal");
          });
          
          $(document).ready(function() {
            setTimeout(function() {
              $('#flash').slideUp("normal");
            }, 5000);
          });
        </script>
      <% end %>
    </div>
    <!-- Footer -->
    <div id="ft" class="container container_wrap">
      <div class="span-12">
        <%= link_to "Home", root_url %> <span class="pipe">|</span>
        <%= link_to "Blog", posts_url %> <span class="pipe">|</span>
        <%= link_to "People", people_url %> <span class="pipe">|</span>
        <%= link_to "Publications", publications_url %>
      </div>
      <div class="span-12 last" style="text-align:right">
        &copy; <%= Date.today.strftime("%Y") %> 
        <%= link_to "CHIMPS Lab @ HCII, CMU", root_url %>.
        All rights reserved.
        <span class="pipe">|</span>
        
        <% if authorized? %>
          <%= link_to 'Logout', logout_path %>
        <% else %>
          <%= link_to 'Login', login_path %>
        <% end %>
      </div>
    </div>
  </div> <!-- End Container -->

<!-- Javascripts -->
<%= yield :js %>

<!-- Analytics -->
<%= render :partial => "layouts/analytics" %>

</body>
</html>